#! /bin/bash

#
# docker-repl
#
# USAGE:
#     * docker-repl                   # Launch docker with REPL in current path.
#     *  [-s|--with-sudo]             # sudo mode.
#     *  [-h|--help]                  # Show This help.
#
# MIT License
#
# Copyright (c) 2021 Hiroshi IKEGAMI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

__DOCKER_REPL_PROMPT_ORIG="\[\e[1;36m\]\$ \$(__prompt::docker_mode) > \[\e[m\]"
export DOCKER_REPL_DEFAULT_PROMPT="${DOCKER_REPL_DEFAULT_PROMPT:-${__DOCKER_REPL_PROMPT_ORIG}}"
export DOCKER_REPL_LS_CMD="${DOCKER_REPL_LS_CMD}"
export DOCKER_REPL_CAT_CMD="${DOCKER_REPL_CAT_CMD}"

docker::repl::help() {
    cat << HELP
USAGE:
    * docker-repl                   # Launch docker with REPL in current path.
    *  [-h|--help]                  # Show This help.
HELP
    exit 1
}

__prompt::docker_mode() {
    echo ${dockercmd}
}

docker::repl::with_sudo_mode() {
    __DOCKER_REPL_WITH_SUDO_MODE="1"
}

docker::repl::main() {
    if [ "${__DOCKER_REPL_WITH_SUDO_MODE}" = "1" ];then
        dockercmd="sudo docker"
    else
        dockercmd="docker"
    fi

    while true; do
        echo -ne "${DOCKER_REPL_DEFAULT_PROMPT@P}"
        read subcommand

        cmd="${dockercmd} ${subcommand}"

        case "${subcommand}" in
            "help")
                ${dockercmd} --help
                ;;
            "exit")
                echo "bye."
                exit 0
                ;;
            *)
                if [[ ${subcommand} =~ ^!(.*)$ ]]; then
                    ${BASH_REMATCH[1]}
                elif [[ ${subcommand} =~ ^docker[:blank:]*.*$ ]]; then
                    ${subcommand}
                else
                    ${cmd};
                fi
                ;;
        esac
    done
}


if [ "$1" != "--no-rlwrap" ];then
    exec rlwrap --remember $0 --no-rlwrap $@ && exit 0;
fi

optspec=":-:hs"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                with-sudo)
                    docker::repl::with_sudo_mode
                    ;;
                help)
                    docker::repl::help; exit 1
                    ;;
                *)
                    if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                        echo "Unknown option --${OPTARG}" >&2
                    fi
                    ;;
            esac;;
        s)
            docker::repl::with_sudo_mode
            ;;
        h)
            docker::repl::help; exit 1
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            exit 1
            ;;
    esac
done


docker::repl::main && exit 0;

